-- MySQL Script generated by MySQL Workbench
-- Thu Dec 13 20:47:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema athena_core
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `athena_core` ;

-- -----------------------------------------------------
-- Schema athena_core
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `athena_core` DEFAULT CHARACTER SET utf8 ;
USE `athena_core` ;

-- -----------------------------------------------------
-- Table `athena_core`.`an_pontiff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_pontiff` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_pontiff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pontiff_token` VARCHAR(145) NULL,
  `name` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NULL,
  `email` VARCHAR(145) NULL,
  `username` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `status` INT NOT NULL DEFAULT 0,
  `img_path` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `pontiff_token_UNIQUE` (`pontiff_token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_church_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_church_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_church_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_church`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_church` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_church` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `church_token` VARCHAR(145) NULL,
  `company_name` VARCHAR(245) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `logo_path` VARCHAR(245) NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_cardinal_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_cardinal_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_cardinal_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_cardinal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_cardinal` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_cardinal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cardinal_token` VARCHAR(145) NULL,
  `church_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NULL,
  `email` VARCHAR(145) NULL,
  `img_path` VARCHAR(245) NULL,
  `username` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_branch_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_branch_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_branch_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_payment_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_payment_resource` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_payment_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `square_application_id` VARCHAR(145) NULL,
  `square_location_id` VARCHAR(145) NULL,
  `square_access_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `church_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_message_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_message_resource` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_message_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `twilio_account_id` VARCHAR(145) NULL,
  `twilio_auth_token` VARCHAR(145) NULL,
  `twilio_from_num` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `church_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_email_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_email_resource` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_email_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `sendgrid_api_key` VARCHAR(145) NULL,
  `sendgrid_from_email` VARCHAR(245) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_address` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `address_line_1` VARCHAR(245) NULL,
  `address_line_2` VARCHAR(245) NULL,
  `city` VARCHAR(60) NULL,
  `state` VARCHAR(20) NULL,
  `country` VARCHAR(20) NULL,
  `post_code` VARCHAR(12) NULL,
  `cdate` DATETIME NULL,
  `status` INT NOT NULL DEFAULT 0,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_branch` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_token` VARCHAR(145) NULL,
  `branch_name` VARCHAR(145) NULL,
  `description` VARCHAR(2445) NULL,
  `church_id` INT NOT NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `primary_payment_resource_id` INT NOT NULL,
  `primary_message_resource_id` INT NOT NULL,
  `primary_email_resource_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_bishop_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_bishop_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_bishop_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_bishop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_bishop` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_bishop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bishop_token` VARCHAR(145) NULL,
  `name` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NULL,
  `email` VARCHAR(145) NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `img_path` VARCHAR(245) NULL,
  `username` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `bishop_token_UNIQUE` (`bishop_token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preist_token` VARCHAR(145) NULL,
  `name` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NULL,
  `email` VARCHAR(145) NULL,
  `img_path` VARCHAR(245) NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `username` VARCHAR(145) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_branch_preist_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_branch_preist_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_branch_preist_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_type` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_branch_preist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_branch_preist` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_branch_preist` (
  `id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `preist_id` INT NOT NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `hourly_rate` INT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `preist_type` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`, `preist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_godfather_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_godfather_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_godfather_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_godfather_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_godfather_card` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_godfather_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `godfather_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `card_brand` VARCHAR(10) NULL,
  `exp_month` INT NULL,
  `exp_year` INT NULL,
  `last_4` VARCHAR(10) NULL,
  `cardholder_name` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `post_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `godfather_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_godfather`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_godfather` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_godfather` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `godfather_token` VARCHAR(145) NULL,
  `name` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NULL,
  `email` VARCHAR(145) NULL,
  `img_path` VARCHAR(245) NULL,
  `primary_card_id` INT NOT NULL,
  `square_customer_id` VARCHAR(145) NULL,
  `username` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `disciple_token` VARCHAR(145) NULL,
  `name` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NULL,
  `email` VARCHAR(145) NULL,
  `img_path` VARCHAR(245) NULL,
  `school_name` VARCHAR(145) NULL,
  `primary_godfather_id` INT NOT NULL,
  `username` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `status` INT UNIQUE NOT NULL,
  PRIMARY KEY (`id`, `primary_godfather_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_branch_disciple_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_branch_disciple_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_branch_disciple_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_grade` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_grade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `status` INT NOT NULL DEFAULT 0,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_branch_disciple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_branch_disciple` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_branch_disciple` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `current_grade_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `primary_godfather_id` INT NOT NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `branch_id`, `church_id`, `current_grade_id`, `disciple_id`, `primary_godfather_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_godfather_disciple_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_godfather_disciple_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_godfather_disciple_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_godfather_disciple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_godfather_disciple` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_godfather_disciple` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `godfather_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `cdate` DATETIME NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`, `godfather_id`, `disciple_id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_major` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_major` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `record_token` VARCHAR(145) NULL,
  `description` VARCHAR(845) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `church_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_subject` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL,
  `record_token` VARCHAR(145) NULL,
  `code` VARCHAR(45) NULL,
  `price` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `church_id` INT NOT NULL,
  PRIMARY KEY (`id`, `major_id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_major` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_major` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `preist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `major_id`, `branch_id`, `church_id`, `branch_preist_id`, `preist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_course_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_course_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_course_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_course` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `code` VARCHAR(45) NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `start_date` DATE NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `end_date` DATE NULL,
  PRIMARY KEY (`id`, `subject_id`, `major_id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_time_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_time_item` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_time_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weekday` INT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `item_token` VARCHAR(145) NULL,
  `course_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `church_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`, `subject_id`, `major_id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_class_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_class_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_class_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_class` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_class` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `class_token` VARCHAR(145) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `course_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `note` VARCHAR(845) NULL,
  PRIMARY KEY (`id`, `course_id`, `subject_id`, `major_id`, `branch_id`, `church_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_course` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `preist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`, `subject_id`, `major_id`, `branch_id`, `church_id`, `branch_preist_id`, `preist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_class` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `is_checkin` INT NOT NULL DEFAULT 0,
  `checkin_time` DATETIME NULL,
  `branch_preist_id` INT NOT NULL,
  `preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `class_id`, `course_id`, `subject_id`, `major_id`, `branch_id`, `church_id`, `branch_preist_id`, `preist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple_course` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple_course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_disciple_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `godfather_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`, `subject_id`, `major_id`, `branch_id`, `church_id`, `branch_disciple_id`, `disciple_id`, `godfather_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple_class` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `is_checkin` INT NOT NULL DEFAULT 0,
  `checkin_time` DATETIME NULL,
  `hw_score` VARCHAR(145) NULL,
  `quiz_score` VARCHAR(45) NULL,
  `branch_disciple_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `godfather_id` INT NOT NULL,
  PRIMARY KEY (`id`, `class_id`, `course_id`, `subject_id`, `major_id`, `branch_id`, `church_id`, `branch_disciple_id`, `disciple_id`, `godfather_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_group_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_group_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_group_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_group` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_group` (
  `id` INT NOT NULL,
  `group_token` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(845) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `church_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple_group` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple_group` (
  `id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `status` INT NOT NULL DEFAULT 0,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`, `disciple_id`, `group_id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_group` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_group` (
  `id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `branch_preist_id` INT NOT NULL,
  `preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `group_id`, `branch_id`, `church_id`, `branch_preist_id`, `preist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_tutoring_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_tutoring_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_tutoring_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_tutoring`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_tutoring` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_tutoring` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tutoring_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `code` VARCHAR(45) NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `checkin_time` DATETIME NULL,
  `branch_preist_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `preist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`, `branch_preist_id`, `preist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple_tutoring`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple_tutoring` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple_tutoring` (
  `id` INT NOT NULL,
  `tutoring_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `checkin_time` DATETIME NULL,
  `branch_disciple_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `godfather_id` INT NOT NULL,
  `branch_preist_id` INT NOT NULL,
  `preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `tutoring_id`, `branch_id`, `church_id`, `branch_disciple_id`, `disciple_id`, `godfather_id`, `branch_preist_id`, `preist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_payment_type` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_payment_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_order_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_order_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_coin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_coin` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_coin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coin_token` VARCHAR(145) NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `status` INT NOT NULL DEFAULT 0,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_order` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_token` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `payment_type` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `bishop_id` INT NOT NULL,
  `coin_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `godfather_id` INT NOT NULL,
  `branch_disciple_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `godfather_disciple_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`, `bishop_id`, `coin_id`, `disciple_id`, `godfather_id`, `branch_disciple_id`, `godfather_disciple_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `coin_id_UNIQUE` (`coin_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_order_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_order_course` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_order_course` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `record_token` VARCHAR(145) NULL,
  PRIMARY KEY (`id`, `order_id`, `course_id`, `subject_id`, `major_id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_fee_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_fee_item` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_fee_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `order_id` INT NOT NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `name` VARCHAR(145) NULL,
  `status` INT NOT NULL DEFAULT 0,
  `note` VARCHAR(845) NULL,
  PRIMARY KEY (`id`, `order_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_discount_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_discount_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_discount_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_discount_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_discount_type` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_discount_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_discount` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount_token` VARCHAR(145) NULL,
  `amount` INT NULL,
  `rate` INT NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_order_discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_order_discount` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_order_discount` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `record_token` VARCHAR(145) NULL,
  PRIMARY KEY (`id`, `order_id`, `discount_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple_grade` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple_grade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `grade_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `branch_disciple_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `cdate` DATETIME NULL,
  `status` INT NOT NULL DEFAULT 0,
  `udate` DATETIME NULL,
  PRIMARY KEY (`id`, `grade_id`, `branch_id`, `church_id`, `branch_disciple_id`, `disciple_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_payment_record_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_payment_record_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_payment_record_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_payment_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_payment_record` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_payment_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL DEFAULT 0,
  `record_token` VARCHAR(145) NULL,
  `due_date` DATETIME NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `payment_type` INT NOT NULL,
  `square_transaction_id` VARCHAR(245) NULL,
  `order_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `godfather_id` INT NOT NULL,
  `branch_disciple_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  `godfather_disciple_id` INT NOT NULL,
  PRIMARY KEY (`id`, `order_id`, `branch_id`, `church_id`, `disciple_id`, `godfather_id`, `branch_disciple_id`, `godfather_disciple_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `record_token_UNIQUE` (`record_token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_order_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_order_note` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_order_note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` VARCHAR(845) NULL,
  `mark` VARCHAR(145) NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `order_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `bishop_id` INT NOT NULL,
  `record_token` VARCHAR(145) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `order_id`, `branch_id`, `church_id`, `bishop_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_disciple_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_disciple_comment` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_disciple_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `note` VARCHAR(845) NULL,
  `mark` VARCHAR(145) NULL,
  `record_token` VARCHAR(145) NULL,
  `bishop_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `branch_disciple_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `godfather_id` INT NOT NULL,
  `branch_preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `preist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`, `church_id`, `branch_disciple_id`, `disciple_id`, `godfather_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_attendance_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_attendance_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_attendance_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_preist_attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_preist_attendance` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_preist_attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `record_date` DATETIME NULL,
  `cdate` DATETIME NULL,
  `udate` DATETIME NULL,
  `mark` VARCHAR(245) NULL,
  `branch_preist_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL,
  `preist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_preist_id`, `branch_id`, `church_id`, `preist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_payment_tender_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_payment_tender_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_payment_tender_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_payment_tender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_payment_tender` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_payment_tender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `square_tender_id` VARCHAR(145) NULL,
  `square_tender_type` VARCHAR(12) NULL,
  `note` VARCHAR(845) NULL,
  `amount` INT NULL,
  `payment_record_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `godfather_id` INT NOT NULL,
  `branch_disciple_id` INT NOT NULL,
  `godfather_disciple_id` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `payment_record_id`, `order_id`, `branch_id`, `church_id`, `disciple_id`, `godfather_id`, `branch_disciple_id`, `godfather_disciple_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_group_message_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_group_message_status` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_group_message_status` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `athena_core`.`an_group_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_group_message` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_group_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_token` VARCHAR(145) NULL,
  `message` VARCHAR(2445) NULL,
  `udate` DATETIME NULL,
  `cdate` DATETIME NULL,
  `bishop_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `type` INT NOT NULL,
  `status` INT UNIQUE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `bishop_id`, `branch_id`, `church_id`, `group_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_sms_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_sms_record` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_sms_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `group_message_id` INT NOT NULL,
  `bishop_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `cell` VARCHAR(45) NULL,
  `twilio_sid` VARCHAR(45) NULL,
  `message` VARCHAR(2545) NULL,
  `twilio_sms_status` VARCHAR(45) NULL,
  `type` INT NULL,
  `branch_disciple_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `godfather_id` INT NOT NULL,
  `branch_preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `preist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `group_id`, `group_message_id`, `bishop_id`, `branch_id`, `church_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `athena_core`.`an_email_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athena_core`.`an_email_record` ;

CREATE TABLE IF NOT EXISTS `athena_core`.`an_email_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_message_id` INT NOT NULL,
  `bishop_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `church_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `message` VARCHAR(2545) NULL,
  `email` VARCHAR(145) NULL,
  `type` INT NOT NULL,
  `branch_disciple_id` INT NOT NULL,
  `disciple_id` INT NOT NULL,
  `branch_preist_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `preist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `group_message_id`, `bishop_id`, `branch_id`, `church_id`, `group_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
